# Generated by Django 5.2.8 on 2025-12-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_department', models.CharField(max_length=30)),
                ('student_course', models.CharField(max_length=30)),
                ('student_sem', models.CharField(max_length=30)),
                ('student_email', models.CharField(max_length=100)),
                ('student_contact', models.CharField(max_length=20)),
                ('student_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_subject', models.CharField(max_length=100)),
                ('mark_total', models.IntegerField()),
                ('mark_sem', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_student')),
            ],
        ),
    ]
