# Generated by Django 5.2.8 on 2025-11-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
