# Generated by Django 6.0 on 2025-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_contact', models.CharField(max_length=50)),
                ('staff_designation', models.CharField(max_length=200)),
                ('staff_password', models.CharField(max_length=50)),
            ],
        ),
    ]
