# Generated by Django 6.0 on 2025-12-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
