# Generated by Django 6.0 on 2025-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='staff_photo',
            field=models.FileField(upload_to='Assets/Staff/Photo/'),
        ),
    ]
