# Generated by Django 6.0 on 2025-12-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_semester_alter_tbl_staff_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear_year', models.CharField(max_length=50)),
            ],
        ),
    ]
