# Generated by Django 6.0 on 2025-12-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tbl_subject',
            name='semester',
        ),
        migrations.DeleteModel(
            name='tbl_course',
        ),
        migrations.DeleteModel(
            name='tbl_subject',
        ),
    ]
