# Generated by Django 6.0 on 2025-12-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_assignclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_class',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tbl_class',
            name='semester',
        ),
        migrations.DeleteModel(
            name='tbl_assignclass',
        ),
        migrations.DeleteModel(
            name='tbl_class',
        ),
    ]
