# Generated by Django 6.0 on 2025-12-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_remove_tbl_class_course_remove_tbl_class_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_academicyear')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_class')),
            ],
        ),
    ]
