# Generated by Django 6.0 on 2025-12-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_class_tbl_assignclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignclass',
        ),
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
