# Generated by Django 6.0 on 2025-12-12 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_delete_tbl_assignclass_delete_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_contact', models.CharField(max_length=50)),
                ('staff_photo', models.FileField(upload_to='Assets/Staff/Photo/')),
                ('staff_gender', models.CharField(max_length=200)),
                ('staff_dob', models.DateField()),
                ('staff_qualification', models.CharField(max_length=200)),
                ('staff_role', models.CharField(max_length=200)),
                ('staff_password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_academicyear')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_class')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
