# Generated by Django 6.0 on 2025-12-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_tbl_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_details', models.CharField(max_length=200)),
                ('book_photo', models.FileField(upload_to='Assets/Book/Photos/')),
                ('book_author', models.CharField(max_length=50)),
                ('book_status', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
            ],
        ),
    ]
