# Generated by Django 6.0 on 2026-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=50)),
                ('info_details', models.CharField(max_length=200)),
                ('info_file', models.FileField(upload_to='Assets/Admin/Photo')),
            ],
        ),
    ]
