# Generated by Django 6.0 on 2026-01-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
