# Generated by Django 6.0 on 2026-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_tbl_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_staff',
            name='staff_role',
            field=models.IntegerField(null=True),
        ),
    ]
