# Generated by Django 6.0 on 2026-02-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_tbl_addon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_info',
        ),
    ]
