# Generated by Django 6.0 on 2026-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_delete_tbl_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=50)),
                ('announcement_details', models.CharField(max_length=200)),
                ('announcement_file', models.FileField(upload_to='Assets/Admin/Photo')),
            ],
        ),
    ]
