# Generated by Django 6.0 on 2026-02-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0036_tbl_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_announcement',
        ),
    ]
