# Generated by Django 6.0 on 2025-12-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_exam'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_classsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_assignclass')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_semester')),
            ],
        ),
    ]
