# Generated by Django 6.0 on 2025-12-19 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_book'),
        ('Staff', '0002_tbl_classsem'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(max_length=200)),
                ('notes_file', models.FileField(upload_to='Assets/Staff/Photo')),
                ('notes_status', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
