# Generated by Django 6.0 on 2025-12-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_tbl_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_notes',
        ),
    ]
