# Generated by Django 6.0 on 2026-01-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_book'),
        ('Staff', '0006_tbl_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_internalmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalmark_date', models.DateField(auto_now_add=True)),
                ('internalmark_mark', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
