# Generated by Django 6.0 on 2026-01-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_timetable'),
        ('Staff', '0007_tbl_internalmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.CharField(max_length=2)),
                ('status', models.IntegerField(default=0)),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_semester')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
