# Generated by Django 6.0 on 2026-01-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_timetable'),
        ('Staff', '0008_tbl_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(auto_now_add=True)),
                ('leave_fromdate', models.DateField()),
                ('leave_todate', models.DateField()),
                ('leave_reason', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
