# Generated by Django 6.0 on 2026-01-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_tbl_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_leave',
        ),
    ]
