# Generated by Django 6.0 on 2026-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0012_tbl_fee'),
        ('User', '0023_delete_tbl_assignmentbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignments',
        ),
    ]
