# Generated by Django 6.0 on 2026-01-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_alter_tbl_staff_staff_role'),
        ('Staff', '0013_delete_tbl_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_title', models.CharField(max_length=200)),
                ('assignments_topic', models.FileField(upload_to='Assets/Staff/Photo')),
                ('assignments_date', models.DateField(auto_now_add=True)),
                ('assignments_duedate', models.DateField()),
                ('assignments_status', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
