# Generated by Django 6.0 on 2026-01-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0015_tbl_exammark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_exammark',
        ),
    ]
