# Generated by Django 6.0 on 2026-01-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_alter_tbl_staff_staff_role'),
        ('Staff', '0016_delete_tbl_exammark'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_exammark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exammark_examtype', models.CharField(max_length=200)),
                ('exammark_mark', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
