# Generated by Django 6.0 on 2026-02-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0017_tbl_exammark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_addon',
            field=models.IntegerField(default=0),
        ),
    ]
