# Generated by Django 6.0 on 2026-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0018_tbl_user_user_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fee',
            name='add_on',
            field=models.IntegerField(default=0),
        ),
    ]
