# Generated by Django 6.0 on 2026-02-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0019_tbl_fee_add_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fee',
            name='course_amount',
            field=models.IntegerField(default=0),
        ),
    ]
