# Generated by Django 6.0 on 2026-02-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0020_tbl_fee_course_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_fee',
            name='course_amount',
        ),
    ]
