# Generated by Django 6.0 on 2026-02-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0022_tbl_examresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_examresult',
        ),
    ]
