# Generated by Django 6.0 on 2026-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0026_tbl_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_scpa',
            field=models.CharField(null=True),
        ),
    ]
