# Generated by Django 6.0 on 2026-02-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0027_tbl_user_user_scpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_scpa',
        ),
    ]
