# Generated by Django 6.0 on 2026-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0028_remove_tbl_user_user_scpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examresult',
            name='examresult_scpa',
            field=models.CharField(null=True),
        ),
    ]
