# Generated by Django 6.0 on 2026-02-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0029_tbl_examresult_examresult_scpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_examresult',
        ),
    ]
