# Generated by Django 6.0 on 2026-02-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0032_tbl_scpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scpa',
        ),
    ]
