# Generated by Django 6.0 on 2026-02-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_tbl_announcement'),
        ('Staff', '0033_delete_tbl_scpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scpa_mark', models.CharField(verbose_name=200)),
                ('scpa_status', models.CharField(verbose_name=200)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
