from django.urls import path
from Admin import views

app_name = "Admin"

urlpatterns = [
    path('District/',views.District,name="District"),
    path('deldistrict/<int:did>',views.deldistrict,name="deldistrict"),
    path('editdistrict/<int:eid>',views.editdistrict,name="editdistrict"),
    path('AdminRegistration/',views.AdminRegistration,name="AdminRegistration"),
    path('deladmin/<int:aid>',views.deladmin,name="deladmin"),
    path('editadmin/<int:eaid>',views.editadmin,name="editadmin"),
    path('Category/',views.Category,name="Category"),
    path('delcategory/<int:cid>',views.delcategory,name="delcategory"),
    path('editcategory/<int:ecid>',views.editcategory,name="editcategory"),
    path('Place/',views.Place,name="Place"),
    path('delplace/<int:did>',views.delplace,name="delplace"),
    path('editplace/<int:eid>',views.editplace,name="editplace"),
    path('Subcategory/',views.Subcategory,name="Subcategory"),
    path('delsub/<int:did>',views.delsub,name="delsub"),
    path('editsub/<int:eid>',views.editsub,name="editsub"),
    path('HomePage/',views.HomePage,name="HomePage"),
    path('UserList/',views.UserList,name="UserList"),
    path('ViewComplaint/',views.ViewComplaint,name="ViewComplaint"),
    path('Reply/<int:id>/',views.Reply,name="Reply"),
    path('ViewFeedback/',views.ViewFeedback,name="ViewFeedback"),
    path('Department/',views.Department,name="Department"),
    path('Course/',views.Course,name="Course"),
    path('deldepartment/<int:did>',views.deldepartment,name="deldepartment"),
    path('editdepartment/<int:eid>',views.editdepartment,name="editdepartment"),
    path('delcourse/<int:did>',views.delcourse,name="delcourse"),
    path('editcourse/<int:eid>',views.editcourse,name="editcourse"),
    path('StaffRegistration/',views.StaffRegistration,name="StaffRegistration"),
    path('delstaff/<int:did>',views.delstaff,name="delstaff"),
    path('Semester/',views.Semester,name="Semester"),
    path('delsemester/<int:did>',views.delsemester,name="delsemester"),
    path('AcademicYear/',views.AcademicYear,name="AcademicYear"),
    path('delyear/<int:did>',views.delyear,name="delyear"),
    path('Subject/',views.Subject,name="Subject"),
    path('delsubjects/<int:did>',views.delsubjects,name="delsubjects"),
    path('AjaxCourse/',views.AjaxCourse,name="AjaxCourse"),
    path('Class/',views.Class,name="Class"),
    path('delclass/<int:did>',views.delclass,name="delclass"),
    path('StaffList/',views.StaffList,name="StaffList"),
    path('AssignClass/',views.AssignClass,name="AssignClass"),
    path('AssignClass/<int:aid>',views.AssignClass,name="AssignClass"),
    path('AjaxClass/',views.AjaxClass,name="AjaxClass"),
    path('AssignSubject/',views.AssignSubject,name="AssignSubject"),
    path('Assignsubject/<int:aid>',views.AssignSubject,name="AssignSubject"),
    path('AjaxSubject/',views.AjaxSubject,name="AjaxSubject"),
    path('delsubject/<int:did>',views.delsubject,name="delsubject"),
    path('Exam/',views.Exam,name="Exam"),
    path('delexam/<int:did>',views.delexam,name="delexam"),
    path('ViewCertificateRequest/',views.ViewCertificateRequest,name="ViewCertificateRequest"),
    path('Accept/<int:aid>',views.Accept,name="Accept"),
    path('Reject/<int:rid>',views.Reject,name="Reject"),
    path('ViewExamRegistration/',views.ViewExamRegistration,name="ViewExamRegistration"),
    path('Genre/',views.Genre,name="Genre"),
    path('delgenre/<int:did>',views.delgenre,name="delgenre"),
    path('Book/',views.Book,name="Book"),
    path('delbook/<int:did>',views.delbook,name="delbook"),

    path("timetable/", views.timetable, name="timetable"),
    path("savetimetable/", views.save_timetable, name="save_timetable"),
    path("viewtimetable/", views.admin_view_timetable, name="ViewTimeTable"),
    path("ViewLeaveRequest/",views.ViewLeaveRequest,name="ViewLeaveRequest"),
    path('Accept/<int:aid>',views.Accept,name="Accept"),
    path('Reject/<int:rid>',views.Reject,name="Reject"),
    path('Announcement/',views.Announcement,name="Announcement"),
    path('delinfo/<int:did>',views.delinfo,name="delinfo"),


   
]