# Generated by Django 6.0 on 2025-12-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0006_remove_tbl_feedback_user_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
