# Generated by Django 6.0 on 2025-12-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0023_tbl_staff_tbl_assignclass'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=200)),
                ('user_gender', models.CharField(max_length=200)),
                ('user_dob', models.DateField()),
                ('user_photo', models.FileField(upload_to='Assets/User/Photo')),
                ('user_password', models.CharField(max_length=50)),
                ('assignclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_assignclass')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
