# Generated by Django 6.0 on 2026-02-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_delete_tbl_user'),
        ('Staff', '0021_remove_tbl_fee_course_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.CharField(max_length=200)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
