# Generated by Django 6.0 on 2026-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notification',
            name='notification_status',
            field=models.IntegerField(default=0),
        ),
    ]
