# Generated by Django 6.0 on 2025-12-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
