# Generated by Django 6.0 on 2025-12-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_tbl_classsem'),
        ('User', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_certificaterequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificaterequest_type', models.CharField(max_length=50)),
                ('certificaterequest_content', models.CharField(max_length=200)),
                ('certificaterequest_date', models.DateField(auto_now_add=True)),
                ('certificaterequest_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
