# Generated by Django 6.0 on 2025-12-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_exam'),
        ('Staff', '0002_tbl_classsem'),
        ('User', '0010_tbl_certificaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examregistration_date', models.DateField(auto_now_add=True)),
                ('examregistration_status', models.IntegerField(default=0)),
                ('examregistration_hallticket', models.CharField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
