# Generated by Django 6.0 on 2025-12-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_tbl_assignments'),
        ('User', '0011_tbl_examregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignmentbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentbody_file', models.FileField(upload_to='Assets/User/Photo')),
                ('assignmentbody_status', models.IntegerField(default=0)),
                ('assignmentbody_date', models.DateField(auto_now_add=True)),
                ('assignmentbody_mark', models.CharField(max_length=50)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_assignments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
