# Generated by Django 6.0 on 2025-12-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_assignmentbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignmentbody',
        ),
    ]
