# Generated by Django 6.0 on 2026-01-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
