# Generated by Django 6.0 on 2026-01-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_tbl_stock'),
        ('Staff', '0011_tbl_leave'),
        ('User', '0017_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('issue_status', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.tbl_user')),
            ],
        ),
    ]
