# Generated by Django 6.0 on 2026-01-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_tbl_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_issue',
        ),
    ]
