# Generated by Django 6.0 on 2026-01-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
