# Generated by Django 6.0 on 2026-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignmentbody',
        ),
    ]
